trigger:
  tags:
    include:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-dev"

variables:
  prerelase: false
  ${{ if contains(variables['Build.SourceBranch'], '-dev') }}:
    prerelease: true

name: $(BuildID)-$(Build.SourceBranchName)

resources:
  - repo: self

stages:
  - stage: buildApp
    displayName: Build App
    jobs:
      - job: buildApp
        displayName: Build App
        steps:
          - script: chmod +x ./gradlew
            displayName: Change wrapper permissions
          - script: echo $KEYSTORE | base64 --decode > keystore.jks
            displayName: Decode Keystore
            env:
              KEYSTORE: $(keystore)
          - script: ./gradlew :app:assembleRelease
            displayName: Assemble Release
            env:
              SIGNING_KEY_ALIAS: $(alias)
              SIGNING_KEY_PASSWORD: $(key_password)
              SIGNING_STORE_PASSWORD: $(keystore_password)
          - publish: app/build/outputs/apk/release/app-release.apk
            artifact: itlab-mobile-android
      - job: createRelease
        displayName: Create Release
        condition: succeeded()
        steps:
          - task: GitHubRelease@1
            displayName: Create Github Release
            inputs:
              gitHubConnection: 'Suput''s PAT Droid'
              repositoryName: '$(Build.Repository.Name)'
              action: 'create'
              target: '$(Build.SourceVersion)'
              tagSource: 'gitTag'
              title: 'Release $(Build.SourceBranchName)'
              releaseNotesFilePath: '.github/contents/release.md'
              isPreRelease: ${{ variables.prerelease }}
              changeLogCompareToRelease: 'lastFullRelease'
              changeLogType: 'commitBased'
          - task: SlackPoster@2
            displayName: Send Notification to Slack
            inputs:
              UserName: 'RTUITLab'
              Message: |
                :tada: New release $(Build.SourceBranchName) is already available! :tada:
                Visit <this page> to see what's new
              ApiToken: '$(slack_token)'
              Channel: '#itlab-mobile-apks'
              IconUrl: 'https://files.rtuitlab.dev/logo/logo.png'
              NeverFails: false
