name: Android CI Workflow

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  # test:
  #   name: Run Unit Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Setup JDK
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8
  #     - name: Run Tests
  #       run: bash ./gradlew test --stacktrace
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Assemble Debug
        run: ./gradlew assembleDebug
      - name: Assemble Release
        run: ./gradlew assembleRelease

      - name: Upload APKs
        uses: actions/upload-artifact@v2
        with:
          name: ITLab-Modile-Android_Build
          path: |
            app/build/outputs/apk/debug/**.apk
            app/build/outputs/apk/release/**.apk
