name: Android CI Workflow

on:
  push:
    branches:
      - master
    tags:
      - develop

jobs:
  build_release_apk:
    name: Generate Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Assemble Release
        run: ./gradlew assembleRelease

  build_debug_apk:
    name: Generate Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Assemble Debug
        run: ./gradlew assembleDebug

  publish_artifacts:
    needs: [build_release_apk, build_debug_apk]
    name: Publish artifacts to Github
    runs-on: ubuntu-latest
    steps:
      - name: Upload APKs
        uses: actions/upload-artifact@v2
        with:
          name: ITLab-Modile-Android_Build
          path: |
            app/build/outputs/apk/debug/**.apk
            app/build/outputs/apk/release/**.apk

  slack_publish:
    needs: [publish_artifacts]
    runs-on: ubuntu-latest
    name: Upload APK to Slack
    steps:
      - name: Upload to slack
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}
          path: app/build/outputs/apk/release/**.apk
          channel: itlab-mobile-apks
          filename: ITLab-Mobile-Release
          filetype: apk
          initial_comment: |
            Use https://github.com/RTUITLab/ITLab-Android/actions page to download Debug version of this app
          title: ITLab-Mobile-Release