name: Android CI Workflow

on:
  push:
    branches:
      - master
    tags:
      - develop

jobs:
  build_release_apk:
    name: Generate Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Decode Keystore
        run: echo ${{ secrets.KEYSTORE }} | base64 --decode > keystore.jks

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Assemble Release
        run: ./gradlew :app:assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Release_Build
          path: app/build/outputs/apk/release/app-release.apk
  slack_publish:
    needs: [build_release_apk]
    runs-on: ubuntu-latest
    name: Upload APK to Slack
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Release_Build
          path: app/artifacts

      - name: Upload to slack
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}
          path: ./app/artifacts/app-release.apk
          channel: itlab-mobile-apks
          filetype: apk
          filename: ITLab-Mobile.apk
          title: ITLab-Mobile-Release
