name: Android CI Workflow

on:
  push:
    branches:
      - master
    tags:
      - develop

jobs:
  build_release_apk:
    name: Generate Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Assemble Release
        run: |
          ./gradlew assembleRelease
          mv app/build/outputs/apk/release/*.apk app/build/outputs/apk/release/app-release.apk
        
      - name: Upload APKs
        uses: actions/upload-artifact@v2
        with:
          name: Release_Build
          path: app/build/outputs/apk/release/app-release.apk

  build_debug_apk:
    name: Generate Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Assemble Debug
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: Debug_Build
          path: app/build/outputs/apk/debug/**.apk

  slack_publish:
    needs: [build_release_apk]
    runs-on: ubuntu-latest
    name: Upload APK to Slack
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Release_Build
          path: app/artifacts

      - name: Upload to slack
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}
          path: ./app/artifacts/app-release.apk
          channel: itlab-mobile-apks
          filetype: apk
          filename: ITLab-Mobile-Release.apk
          initial_comment: |
            <https://api.github.com/repos/${{ github.repository }}/actions/artifacts|Debug version of app>
            <https://github.com/actions/upload-artifact/issues/50|Чтобы нормально скачивать артифакты надо следить за этим issue>
          title: ITLab-Mobile-Release